"use client";

import { useEffect, useMemo, useState } from "react";

const assets = [
  { s: "MSFT", n: "Microsoft", type: "Actions US", risk: "Modéré", thesis: "Cloud, IA et discipline de marge", cik: "0000789019", sources: ["SEC EDGAR", "Investor relations"] },
  { s: "ASML", n: "ASML Holding", type: "Actions Europe", risk: "Modéré", thesis: "Goulot d’étranglement de la lithographie", sources: ["Rapports annuels", "Investor relations"] },
  { s: "MC", n: "LVMH", type: "Actions France", risk: "Modéré", thesis: "Qualité de marque, sensible au cycle chinois", sources: ["Document d’enregistrement", "Investor relations"] },
  { s: "QQQ", n: "Invesco QQQ", type: "ETF", risk: "Modéré", thesis: "Exposition Nasdaq et mégacaps technologiques", sources: ["ETF factsheet", "SEC EDGAR"] },
  { s: "BTC", n: "Bitcoin", type: "Crypto", risk: "Élevé", thesis: "Actif macro liquide, volatilité structurelle", sources: ["CoinGecko", "On-chain / protocol"] },
  { s: "ETH", n: "Ethereum", type: "Crypto", risk: "Élevé", thesis: "Adoption du protocole, frais et staking", sources: ["CoinGecko", "Protocol docs"] },
  { s: "DOGE", n: "Dogecoin", type: "Memecoin", risk: "Très élevé", thesis: "Narratif et liquidité : allocation plafonnée", sources: ["CoinGecko", "Market data"] },
  { s: "RKLB", n: "Rocket Lab", type: "Actions US", risk: "Très élevé", thesis: "Spatial en croissance, risque de financement", cik: "0001819994", sources: ["SEC EDGAR", "Investor relations"] },
];
const sourceCatalog = [
  { name: "SEC EDGAR", state: "Disponible", type: "Primaire · États-Unis", text: "Dépôts 10-K, 10-Q, 8-K et faits XBRL des entreprises américaines.", href: "https://www.sec.gov/edgar/search/", use: "Fondamentaux, risques, événements, liens de preuve" },
  { name: "FRED", state: "Clé gratuite", type: "Primaire · Macro", text: "Séries macroéconomiques de la Federal Reserve Bank of St. Louis.", href: "https://fred.stlouisfed.org/docs/api/fred/", use: "Taux, inflation, emploi, liquidité" },
  { name: "CoinGecko", state: "Clé gratuite", type: "Crypto", text: "Marchés, volumes et historique pour crypto-actifs; limites de l’offre gratuite.", href: "https://www.coingecko.com/en/api", use: "Prix, capitalisation, volumes, historique" },
  { name: "Investor relations", state: "Disponible", type: "Primaire · Émetteurs", text: "Rapports annuels, résultats, présentations et calendriers publiés par les sociétés.", href: "https://www.microsoft.com/en-us/Investor/", use: "Thèse, guidance, transcription, calendrier" },
  { name: "TradingView", state: "Lien externe", type: "Graphiques", text: "Passerelle vers l’analyse graphique et la cotation de l’instrument sélectionné.", href: "https://www.tradingview.com/", use: "Consultation graphique; aucune exécution d’ordre" },
];
const researchTabs = ["Vue d’ensemble", "Fondamentaux", "Résultats", "Valorisation", "Actualités", "Risques", "Sources"];

function useStoredState(key, fallback) {
  const [value, setValue] = useState(fallback);
  useEffect(() => { const saved = window.localStorage.getItem(key); if (saved) { try { setValue(JSON.parse(saved)); } catch {} } }, [key]);
  useEffect(() => { window.localStorage.setItem(key, JSON.stringify(value)); }, [key, value]);
  return [value, setValue];
}

export default function Home() {
  const [view, setView] = useState("dashboard"), [selected, setSelected] = useState(assets[0]), [tab, setTab] = useState("Vue d’ensemble"), [filter, setFilter] = useState("Tous");
  const [watch, setWatch] = useStoredState("horizon-watchlist-v1", ["MSFT", "ASML", "QQQ"]);
  const [profile, setProfile] = useStoredState("horizon-profile-v1", null);
  const [notes, setNotes] = useStoredState("horizon-notes-v1", {});
  const [profileOpen, setProfileOpen] = useState(false), [notice, setNotice] = useState(""), [query, setQuery] = useState("");
  const flash = (message) => { setNotice(message); window.setTimeout(() => setNotice(""), 2800); };
  const openResearch = (asset, nextTab = "Vue d’ensemble") => { setSelected(asset); setTab(nextTab); setView("research"); };
  const add = (symbol) => setWatch((current) => current.includes(symbol) ? (flash(`${symbol} est déjà dans votre liste.`), current) : (flash(`${symbol} ajouté à votre watchlist.`), [...current, symbol]));
  const remove = (symbol) => { setWatch((current) => current.filter((item) => item !== symbol)); flash(`${symbol} retiré de votre watchlist.`); };
  const visible = useMemo(() => assets.filter((asset) => (filter === "Tous" || asset.type === filter) && (`${asset.s} ${asset.n}`.toLowerCase().includes(query.toLowerCase()))), [filter, query]);
  return <div className="app"><aside><div className="brand"><b>H</b><strong>HORIZON</strong><small>RESEARCH OS</small></div><button className="workspace" onClick={() => setProfileOpen(true)}><i/><span><b>{profile?.name || "Espace personnel"}</b><small>{profile ? "Profil local enregistré" : "Configurer ce navigateur"}</small></span><em>⌄</em></button><nav><label>ESPACE DE TRAVAIL</label><Nav icon="▦" text="Command center" active={view === "dashboard"} on={() => setView("dashboard")}/><Nav icon="◇" text="Univers d’actifs" active={view === "universe"} on={() => setView("universe")}/><Nav icon="◎" text="Ma watchlist" badge={watch.length} active={view === "watchlist"} on={() => setView("watchlist")}/><Nav icon="◷" text="Calendrier des risques" active={view === "calendar"} on={() => setView("calendar")}/><label>INTELLIGENCE</label><Nav icon="▤" text="Cockpit de recherche" active={view === "research"} on={() => setView("research")}/><Nav icon="✦" text="Brief quotidien" active={view === "briefing"} on={() => setView("briefing")}/><Nav icon="◌" text="Sources & couverture" active={view === "sources"} on={() => setView("sources")}/></nav><div className="sidebottom"><p><i/> Mode local · aucun ordre ni conseil</p><button className="local" onClick={() => setProfileOpen(true)}>{profile ? "Modifier mon profil" : "Créer mon espace"}</button></div></aside><main><header><div><b>{titleFor(view)}</b><span> / Recherche multi-actifs</span></div><div className="search"><span>⌕</span><input value={query} onChange={(event) => { setQuery(event.target.value); if (event.target.value) setView("universe"); }} placeholder="Rechercher un actif"/><kbd>⌘ K</kbd></div></header>{notice && <div className="notice" role="status">{notice}</div>}{view === "dashboard" && <Dashboard watch={watch} openResearch={openResearch} setView={setView}/>} {view === "universe" && <Universe assets={visible} filter={filter} setFilter={setFilter} add={add} openResearch={openResearch}/>} {view === "watchlist" && <Watchlist watch={watch} add={() => setView("universe")} remove={remove} openResearch={openResearch}/>} {view === "research" && <Research asset={selected} tab={tab} setTab={setTab} add={add} note={notes[selected.s] || ""} setNote={(value) => setNotes((all) => ({ ...all, [selected.s]: value }))}/>} {view === "calendar" && <Calendar openResearch={openResearch}/>} {view === "briefing" && <Briefing openResearch={openResearch}/>} {view === "sources" && <Sources/>}</main>{profileOpen && <Profile initial={profile} close={() => setProfileOpen(false)} save={(next) => { setProfile(next); setProfileOpen(false); flash("Votre espace local est prêt."); }}/>}</div>;
}
function Nav({ icon, text, on, active, badge }) { return <button className={`nav ${active ? "active" : ""}`} onClick={on}><span>{icon}</span>{text}{badge !== undefined && <b>{badge}</b>}</button>; }
function titleFor(view) { return ({ dashboard: "COMMAND CENTER", universe: "UNIVERS D’ACTIFS", watchlist: "MA WATCHLIST", research: "COCKPIT DE RECHERCHE", calendar: "CALENDRIER DES RISQUES", briefing: "BRIEF QUOTIDIEN", sources: "SOURCES & COUVERTURE" })[view]; }
function Dashboard({ watch, openResearch, setView }) { return <section><div className="hero"><div><small>RECHERCHE STRUCTURÉE · MODE LOCAL</small><h1>Une décision documentée,<br/><em>pas une intuition.</em></h1><p>Construisez une thèse, reliez-la à une source et définissez le risque avant d’agir.</p><button className="primary" onClick={() => setView("universe")}>Explorer l’univers</button></div><div className="riskbox"><small>VOTRE COUVERTURE</small><b>{watch.length}<em> actifs suivis</em></b><p>Chaque ajout est conservé dans ce navigateur.</p></div></div><div className="metrics"><Metric n="3" t="Sources primaires prêtes" sub="SEC, macro et émetteurs"/><Metric n="À qualifier" t="Régime de risque" sub="Pas de signal automatique"/><Metric n="07" t="Événements à vérifier" sub="Calendrier de démonstration"/><Metric n="0" t="Ordres exécutés" sub="Horizon ne passe aucun ordre"/></div><div className="twocol"><section className="panel"><small>RESEARCH RADAR</small><h2>Commencer par une question</h2>{assets.slice(0, 4).map((asset) => <button className="radar" key={asset.s} onClick={() => openResearch(asset)}><b>{asset.s}</b><span>{asset.n}<small>{asset.thesis}</small></span><em>{asset.risk}</em><strong>›</strong></button>)}</section><section className="panel"><small>DISCIPLINE D’INVESTISSEMENT</small><h2>Avant toute décision</h2><p className="briefline"><b>01</b> Lire la source primaire, pas le résumé.</p><p className="briefline"><b>02</b> Écrire ce qui invaliderait la thèse.</p><p className="briefline"><b>03</b> Ajuster l’exposition au risque réellement assumé.</p><button className="link" onClick={() => setView("sources")}>Voir les sources connectables →</button></section></div></section>; }
function Metric({ n, t, sub }) { return <article className="metric"><small>{t.toUpperCase()}</small><b>{n}</b><p>{sub}</p><i/></article>; }
function Universe({ assets: visible, filter, setFilter, add, openResearch }) { const filters = ["Tous", "Actions US", "Actions Europe", "Actions France", "ETF", "Crypto", "Memecoin"]; return <section><Title eyebrow="DÉCOUVERTE MULTI-ACTIFS" title="Univers d’actifs" text="Des instruments à étudier, non des recommandations. Les données de marché ne seront affichées que si elles sont sourcées."/><div className="chips">{filters.map((item) => <button className={filter === item ? "chosen" : ""} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="cards">{visible.map((asset) => <article className="assetcard" key={asset.s}><header><b>{asset.s.slice(0, 2)}</b><span><small>{asset.type}</small><h3>{asset.n}</h3></span><em>{asset.risk}</em></header><p>{asset.thesis}</p><div className="sourcechips">{asset.sources.map((source) => <span key={source}>{source}</span>)}</div><div className="assetfoot"><button onClick={() => openResearch(asset)}>Ouvrir la recherche</button><button onClick={() => add(asset.s)}>+ Watchlist</button><a target="_blank" rel="noreferrer" href={`https://www.tradingview.com/symbols/${asset.s}/`}>TradingView ↗</a></div></article>)}</div>{!visible.length && <Empty/>}</section>; }
function Watchlist({ watch, add, remove, openResearch }) { const followed = assets.filter((asset) => watch.includes(asset.s)); return <section><Title eyebrow="RECHERCHE PERSONNELLE" title="Ma watchlist" text="La liste est réellement conservée sur cet appareil. La synchronisation entre appareils viendra avec Neon et une authentification." action={<button className="primary" onClick={add}>+ Ajouter un actif</button>}/>{followed.length ? <div className="watchtable"><div className="thead"><span>ACTIF</span><span>THÈSE</span><span>RISQUE</span><span>ACTION</span></div>{followed.map((asset) => <div className="trow" key={asset.s}><b>{asset.s}<small>{asset.n}</small></b><span>{asset.thesis}</span><em>{asset.risk}</em><span><button onClick={() => openResearch(asset)}>Recherche</button><button onClick={() => remove(asset.s)}>Retirer</button></span></div>)}</div> : <Empty action={add}/>}</section>; }
function Research({ asset, tab, setTab, add, note, setNote }) { return <section><Title eyebrow="FICHE DE RECHERCHE" title={asset.n} text={`${asset.s} · ${asset.type} · risque ${asset.risk}`} action={<button className="primary" onClick={() => add(asset.s)}>+ Ajouter à la watchlist</button>}/><div className="tabs">{researchTabs.map((item) => <button className={tab === item ? "selected" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</div>{tab === "Sources" ? <AssetSources asset={asset}/> : <ResearchContent asset={asset} tab={tab} note={note} setNote={setNote}/>}</section>; }
function ResearchContent({ asset, tab, note, setNote }) { const content = copyFor(tab); const riskScore = asset.risk === "Très élevé" ? "3.5" : asset.risk === "Élevé" ? "5.5" : "7.0"; return <><div className="researchgrid"><article className="panel large"><small>{tab.toUpperCase()}</small><h2>{content.title}</h2><p>{content.text}</p><div className="scenarios">{content.inputs.map((input) => <div key={input}><small>POINT À VÉRIFIER</small><b>{input}</b></div>)}</div></article><aside className="panel score"><small>LECTURE DU RISQUE</small><b>{riskScore}<em> / 10</em></b><p>Ce n’est pas un score d’achat. C’est la part d’incertitude à documenter.</p><hr/><Score label="Liquidité" value={asset.type === "Memecoin" ? "38%" : "72%"}/><Score label="Risque fondamental" value={asset.risk === "Très élevé" ? "88%" : "52%"}/><Score label="Visibilité des données" value={asset.cik ? "85%" : "52%"}/></aside></div><section className="panel notebook"><small>NOTE PERSONNELLE · ENREGISTRÉE SUR CET APPAREIL</small><h2>Votre thèse de travail</h2><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder={`Ex. Pour ${asset.s}, je surveille…`}/><p>Écrivez la thèse, le catalyseur, l’invalidation et la taille de risque avant toute décision.</p></section></>; }
function Score({ label, value }) { return <div className="scoreline"><span>{label}</span><i><b style={{ width: value }}/></i></div>; }
function copyFor(tab) { const copy = { "Vue d’ensemble": ["Une thèse commence par les faits", "Cette fiche doit être lue à travers son activité, ses risques et les événements à venir. Horizon ne transforme pas cette fiche en ordre d’achat ou de vente.", ["Source primaire la plus récente", "Catalyseur daté", "Point d’invalidation"]], Fondamentaux: ["Des fondamentaux dont chaque chiffre est traçable", "Le modèle de production rapprochera chaque métrique d’un dépôt, d’un rapport annuel ou d’un document de résultats. Les valeurs non sourcées ne seront jamais présentées comme des faits.", ["Croissance du chiffre d’affaires", "Marge et conversion en trésorerie", "Dette, dilution ou bilan"]], Résultats: ["Préparer les résultats avant le titre", "Comparer les indicateurs publiés, les objectifs de direction et les éléments qui changent la trajectoire plutôt que de commenter une réaction de cours isolée.", ["Date et document officiel", "Indicateur opérationnel clé", "Changement de guidance"]], Valorisation: ["La valorisation est une plage, pas une promesse", "Une analyse robuste confronte scénarios, cash-flow et hypothèses. Un prix cible unique peut masquer l’incertitude.", ["Hypothèse de croissance", "Marge normalisée", "Scénario baissier"]], Actualités: ["Le fait avant l’interprétation", "Les actualités devront afficher une date, une source, le fait vérifiable et une note expliquant pourquoi il pourrait compter dans la thèse.", ["Source officielle ou identifiable", "Date / heure", "Lien avec la thèse"]], Risques: ["La contre-thèse mérite le même espace", "Listez les éléments qui pourraient invalider l’idée et les signaux qui imposeraient une révision du dossier.", ["Risque opérationnel", "Risque de valorisation", "Risque de liquidité / volatilité"]] }; const [title, text, inputs] = copy[tab] || copy["Vue d’ensemble"]; return { title, text, inputs }; }
function AssetSources({ asset }) { const edgar = asset.cik ? `https://data.sec.gov/submissions/CIK${asset.cik}.json` : null; return <div className="source-list"><section className="panel"><small>PROVENANCE PAR ACTIF</small><h2>{asset.n}</h2><p>Cette fiche expose la provenance attendue avant d’afficher une conclusion. Un lien externe ouvre la source, il ne valide pas automatiquement une thèse.</p>{asset.sources.map((source) => <div className="source-row" key={source}><b>{source}</b><span>{source === "SEC EDGAR" ? "Dépôts et faits XBRL" : "À qualifier dans la couche de données"}</span>{source === "SEC EDGAR" && edgar ? <a target="_blank" rel="noreferrer" href={edgar}>Ouvrir ↗</a> : <span className="pending">En préparation</span>}</div>)}</section><section className="panel"><small>STATUT DE DONNÉES</small><h2>Ce que nous ne prétendons pas faire</h2><p>Pas de cours temps réel, pas de consensus analystes et pas de recommandation automatisée tant qu’une source autorisée, un horodatage et une méthode ne sont pas en place.</p><a className="buttonlink" target="_blank" rel="noreferrer" href={`https://www.tradingview.com/symbols/${asset.s}/`}>Consulter le graphique ↗</a></section></div>; }
function Calendar({ openResearch }) { return <section><Title eyebrow="MONITEUR D’ÉVÉNEMENTS" title="Calendrier des risques" text="Les dates ci-dessous sont un modèle de workflow. En production, chaque événement sera lié à son émetteur ou à sa publication officielle."/><div className="events">{[["18", "Publication macro", "Inflation US — vérifier la release FRED", "MACRO"], ["22", "Résultats d’entreprise", "Microsoft — rattacher le communiqué et le transcript", "ÉMETTEUR", assets[0]], ["24", "Marché crypto", "Revue hebdomadaire : volatilité et liquidité", "CRYPTO"], ["30", "Revue de portefeuille", "Relire les thèses avant de modifier une exposition", "PROCESSUS"]].map(([date, kind, detail, tag, asset]) => <article key={date + kind}><b>{date}</b><span><small>SEPT. · {kind}</small><h3>{detail}</h3><p>Définir l’impact potentiel, la source et l’action de recherche.</p></span><em>{tag}</em>{asset && <button onClick={() => openResearch(asset, "Résultats")}>Étudier</button>}</article>)}</div></section>; }
function Briefing({ openResearch }) { return <section><Title eyebrow="NOTE DE RECHERCHE" title="Le brief utile ne prédit pas." text="Il résume les faits, précise ce qui a changé et renvoie toujours vers sa source."/><article className="panel essay"><small>STRUCTURE DU BRIEF QUOTIDIEN</small><h2>1. Fait. 2. Impact. 3. Question à tester.</h2><p>Un flux d’actualité sans hiérarchie est du bruit. La couche de données doit assembler les publications officielles, les séries macro et les événements de portefeuille, puis laisser l’utilisateur remonter au document d’origine.</p><div className="briefcards"><button onClick={() => openResearch(assets[0], "Sources")}><b>01</b><span><strong>Microsoft</strong> — vérifier la dernière publication et les indicateurs cloud.</span></button><button onClick={() => openResearch(assets[4], "Risques")}><b>02</b><span><strong>Bitcoin</strong> — qualifier le risque de volatilité avant d’interpréter le prix.</span></button></div></article></section>; }
function Sources() { return <section><Title eyebrow="REGISTRE DE DONNÉES" title="Sources, droits et couverture" text="Le principe : privilégier le document primaire, afficher l’horodatage et ne jamais déguiser une donnée de démonstration en donnée de marché."/><div className="source-grid">{sourceCatalog.map((source) => <article className="source-card" key={source.name}><header><span>{source.type}</span><b className={source.state === "Disponible" ? "available" : "key"}>{source.state}</b></header><h2>{source.name}</h2><p>{source.text}</p><div><small>UTILISATION</small><strong>{source.use}</strong></div><a target="_blank" rel="noreferrer" href={source.href}>Documentation / source ↗</a></article>)}</div><section className="panel roadmap"><small>ORDRE D’INTÉGRATION · ZÉRO EURO</small><h2>Fondation de données recommandée</h2><ol><li><b>SEC EDGAR</b><span>Import des fiches et faits financiers US avec cache, horodatage et lien vers le dépôt.</span></li><li><b>FRED</b><span>Ajout des indicateurs macro sélectionnés via une clé gratuite, sans exposer la clé dans le navigateur.</span></li><li><b>CoinGecko</b><span>Marchés crypto et historique avec limites affichées, jamais présenté comme flux haute fréquence.</span></li><li><b>Neon + authentification</b><span>Comptes, watchlists, notes et alertes personnelles synchronisées.</span></li></ol></section></section>; }
function Title({ eyebrow, title, text, action }) { return <div className="title"><div><small>{eyebrow}</small><h1>{title}</h1><p>{text}</p></div>{action}</div>; }
function Empty({ action }) { return <div className="empty"><h2>Aucun actif ne correspond.</h2><p>Essayez une autre catégorie ou ajoutez un actif depuis l’univers.</p>{action && <button className="primary" onClick={action}>Explorer les actifs</button>}</div>; }
function Profile({ initial, close, save }) { const [name, setName] = useState(initial?.name || ""), [horizon, setHorizon] = useState(initial?.horizon || "Long terme"); return <div className="overlay"><form className="login" onSubmit={(event) => { event.preventDefault(); save({ name: name.trim() || "Espace personnel", horizon }); }}><button type="button" aria-label="Fermer" onClick={close}>×</button><small>ESPACE PERSONNEL · LOCAL</small><h2>Configurez ce navigateur.</h2><p>Cette version gratuite conserve votre nom, vos notes et votre watchlist localement. Ce n’est pas encore un compte connecté.</p><label>Nom d’affichage<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Votre nom"/></label><label>Horizon d’investissement<select value={horizon} onChange={(event) => setHorizon(event.target.value)}><option>Long terme</option><option>Moyen terme</option><option>Court terme</option></select></label><button className="primary">Enregistrer mon espace</button></form></div>; }
